// src/components/DocumentsScreen.jsx — FIXED: Full multilingual support
import React, { useState } from 'react';
import { useApp } from '../contexts/AppContext';
import { UI_TEXT, LANG_NAMES, DOC_ITEMS, DOCS_HELP_NOTE } from '../data/translations';
import { LETTERS } from '../data/legalData';

export default function DocumentsScreen() {
  const { lang, navigate, showToast } = useApp();
  const T = UI_TEXT[lang] || UI_TEXT.en;

  // Translated document list
  const DOC_LIST = DOC_ITEMS[lang] || DOC_ITEMS.en;

  const [selectedDoc, setSelectedDoc] = useState(null);

  const copyLetter = (text) => {
    navigator.clipboard.writeText(text)
      .then(() => showToast('✅ ' + (T.copyDoc || 'Copied') + '!'))
      .catch(() => showToast('Select and copy manually'));
  };

  const printLetter = (letter) => {
    const langName = LANG_NAMES[lang] || 'English';
    const dateLang = (UI_TEXT[lang] || UI_TEXT.en).dateLang || 'en-IN';
    const now = new Date().toLocaleDateString(dateLang, { day: 'numeric', month: 'long', year: 'numeric' });

    const printWindow = window.open('', '_blank', 'width=800,height=600');
    printWindow.document.write(`
      <!DOCTYPE html>
      <html lang="${lang}">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${letter.title} — NYAYA</title>
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700;800&family=Noto+Sans+Devanagari&family=Noto+Sans+Telugu&family=Noto+Sans+Tamil&family=Noto+Sans+Kannada&family=Noto+Sans+Malayalam&family=Noto+Sans+Bengali&display=swap" rel="stylesheet">
        <style>
          body {
            font-family: 'Nunito','Noto Sans Devanagari','Noto Sans Telugu','Noto Sans Tamil','Noto Sans Kannada','Noto Sans Malayalam','Noto Sans Bengali',serif;
            max-width: 700px; margin: 40px auto; padding: 20px;
            font-size: 14px; line-height: 1.8; color: #1a1a1a;
          }
          .header { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:3px solid #FF6B00; padding-bottom:16px; margin-bottom:24px; }
          .logo { font-size:24px; font-weight:900; color:#FF6B00; }
          .logo-sub { font-size:11px; color:#888; }
          .lang-tag { background:#FFF0E6; border:1.5px solid #FFD4B3; border-radius:6px; padding:4px 10px; font-size:12px; font-weight:700; color:#FF6B00; }
          .title { font-size:20px; font-weight:900; margin-bottom:8px; }
          .date { font-size:12px; color:#888; text-align:right; margin-bottom:20px; }
          .letter-body { font-family:'Courier New','Noto Sans Devanagari','Noto Sans Telugu',monospace; white-space:pre-wrap; font-size:13px; line-height:2; background:#f9f9f9; padding:20px; border:1px solid #ddd; border-radius:8px; }
          .footer { margin-top:32px; padding-top:16px; border-top:1px solid #E5E7EB; font-size:11px; color:#888; text-align:center; }
          .nyaya-watermark { color:#FF6B00; font-weight:800; }
          @media print { body { margin:20px; } }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="logo">NYAYA — न्याय</div>
            <div class="logo-sub">Free Legal Aid App · Article 39A</div>
          </div>
          <div class="lang-tag">${langName}</div>
        </div>
        <div class="title">${letter.title}</div>
        <div class="date">${now}</div>
        <div class="letter-body">${letter.body}</div>
        <div class="footer">
          Generated by <span class="nyaya-watermark">NYAYA</span> — Free Legal Advisor ·
          For FREE lawyer call 📞 15100 (Article 39A)
        </div>
        <script>window.onload=function(){window.print();};</script>
      </body>
      </html>
    `);
    printWindow.document.close();
  };

  // ── Letter detail view ───────────────────────────────────────────────────
  if (selectedDoc) {
    const letter = LETTERS[selectedDoc];
    const dateLang = (UI_TEXT[lang] || UI_TEXT.en).dateLang || 'en-IN';
    const now = new Date().toLocaleDateString(dateLang, { day: 'numeric', month: 'long', year: 'numeric' });
    return (
      <div style={styles.container}>
        <div style={styles.topbar} className="no-print">
          <button style={styles.backBtn} onClick={() => setSelectedDoc(null)}>‹</button>
          <h2 style={styles.title}>{letter.title}</h2>
        </div>
        <div style={styles.body}>
          <div style={styles.docDetail}>
            <div style={styles.dateRow}>{now}</div>
            <div style={styles.langBadge}>
              {LANG_NAMES[lang] || 'English'}
              <span style={styles.langBadgeNote}> ({LANG_NAMES[lang] || 'English'})</span>
            </div>
            <pre style={styles.letterText}>{letter.body}</pre>
            <div style={styles.docActions} className="no-print">
              <button style={styles.docBtn} onClick={() => copyLetter(letter.body)}>
                📋 {T.copyDoc || 'Copy'}
              </button>
              <button style={{...styles.docBtn, ...styles.docBtnPrimary}} onClick={() => printLetter(letter)}>
                🖨️ {T.printDoc || 'Print'}
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // ── Document grid ────────────────────────────────────────────────────────
  const helpNote = (DOCS_HELP_NOTE[lang] || DOCS_HELP_NOTE.en)(lang);

  return (
    <div style={styles.container}>
      <div style={styles.topbar} className="no-print">
        <button style={styles.backBtn} onClick={() => navigate('home')}>‹</button>
        <h2 style={styles.title}>{T.docsTitle}</h2>
      </div>
      <div style={styles.body}>
        <div style={styles.docGrid}>
          {DOC_LIST.map(doc => (
            <div key={doc.key} style={styles.docCard} onClick={() => setSelectedDoc(doc.key)}>
              <span style={styles.docEm}>{doc.icon}</span>
              <div style={styles.docT}>{doc.titleKey}</div>
              <div style={styles.docD}>{doc.descKey}</div>
            </div>
          ))}
        </div>
        <div style={styles.helpNote}>
          {helpNote}
        </div>
      </div>
    </div>
  );
}

const styles = {
  container: { background: '#F8F5F0', minHeight: '100vh', display: 'flex', flexDirection: 'column' },
  topbar: { background: 'white', padding: '14px 16px', display: 'flex', alignItems: 'center', gap: 12, borderBottom: '1px solid #E5E7EB', position: 'sticky', top: 0, zIndex: 50 },
  backBtn: { width: 36, height: 36, borderRadius: '50%', background: '#F8F5F0', border: 'none', cursor: 'pointer', fontSize: 20, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  title: { fontSize: 18, fontWeight: 800 },
  body: { padding: 16, paddingBottom: 100 },
  docGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 16 },
  docCard: { background: 'white', borderRadius: 16, padding: 18, cursor: 'pointer', transition: 'all 0.25s', boxShadow: '0 2px 16px rgba(0,0,0,0.08)', border: '2px solid transparent' },
  docEm: { fontSize: 30, marginBottom: 8, display: 'block' },
  docT: { fontSize: 13, fontWeight: 800, marginBottom: 3, lineHeight: 1.4 },
  docD: { fontSize: 11, color: '#6B7280', lineHeight: 1.5 },
  helpNote: { background: '#EFF6FF', border: '1px solid #BFDBFE', borderRadius: 12, padding: '12px 16px', fontSize: 13, color: '#2563EB', lineHeight: 1.6 },
  docDetail: { background: 'white', borderRadius: 16, padding: 20, boxShadow: '0 2px 16px rgba(0,0,0,0.08)' },
  dateRow: { fontSize: 12, color: '#6B7280', textAlign: 'right', marginBottom: 6 },
  langBadge: { display: 'inline-block', background: '#FFF0E6', border: '1px solid #FFD4B3', borderRadius: 6, padding: '4px 10px', fontSize: 11, fontWeight: 700, color: '#FF6B00', marginBottom: 14 },
  langBadgeNote: { fontWeight: 400, color: '#6B7280', fontSize: 10 },
  letterText: { fontFamily: "'Courier New', monospace", fontSize: 12, lineHeight: 1.9, color: '#2D2D2D', background: '#F8F5F0', padding: 16, borderRadius: 10, whiteSpace: 'pre-wrap', marginBottom: 16, border: '1px solid #E5E7EB', maxHeight: 380, overflowY: 'auto' },
  docActions: { display: 'flex', gap: 10 },
  docBtn: { flex: 1, padding: 12, borderRadius: 10, border: '2px solid #E5E7EB', background: 'white', fontSize: 13, fontWeight: 700, fontFamily: "'Nunito', sans-serif", cursor: 'pointer', transition: 'all 0.2s' },
  docBtnPrimary: { background: '#FF6B00', borderColor: '#FF6B00', color: 'white' },
};
